### ISSUE TITLE
Getting error targetModel.updateMany is not a function

### ISSUE THREAD

**Issue by singetak** [mintdevops/strapi-connector-mongoose#1]
https://github.com/mintdevops/strapi-connector-mongoose/blob/112ee6f808c3b35494b8bdda8d37a61233e467e4/lib/relations.js#L442

When trying to delete a file that is related to a collection on strapi i get an error here

error TypeError: targetModel.updateMany is not a function
    at Promise.all.entry.(anonymous function).map.val (/node_modules/strapi-connector-mongoose/lib/relations.js:476:40)
    at CoreDocumentArray.map (<anonymous>)
    at CoreDocumentArray.map (/node_modules/mongoose/lib/types/documentarray.js:42:27)
    at Promise.all.associations.map (/node_modules/strapi-connector-mongoose/lib/relations.js:464:42)
    at Array.map (<anonymous>)
    at Function.deleteRelations (/node_modules/strapi-connector-mongoose/lib/relations.js:393:25)
    at deleteOne (/node_modules/strapi-connector-mongoose/lib/queries.js:560:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by nwazuo** [comment]
Same thing here. This only happens(as far as I've observed) only on media related to a collection. 

It actually deletes the resource but returns an error. 

In my case, I use cloudinary to store media assets and it correctly deletes from both cloudinary and media library but still throws this error in the console and in the media library console. 

  
@alexandrebodin @soupette

**Comment by nwazuo** [comment]
Seems like this is the wrong place to drop this. I'm going to search for this in the strapi repository

**Comment by topovik** [comment]
Use it
https://stackoverflow.com/a/71432801/12369840
